# version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}  
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3306:3306"
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "5000:5000"  
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}  
      DB_PASSWORD: ${DB_PASSWORD}  
      DB_NAME: ${DB_NAME}  
    networks:
      - app-network
    depends_on:
      - db

