# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      # dockerfile: DockerFile
    ports:
      - "5000:5000"  
    environment:
      - DB_HOST=${DB_HOST}  
      - DB_USER=${DB_USER}  
      - DB_PASSWORD=${DB_PASSWORD}  
      - DB_NAME=${DB_NAME}  
    depends_on:
      - mysql 

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}  
    volumes:
      # - mysql_data:/var/lib/mysql 

      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

    ports:
      - "3306:3306" 

volumes:
  mysql_data:
