# Dockerfile

# Use Node.js LTS version as the base image
FROM node:18

# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependencies
COPY package.json ./
COPY package-lock.json ./


# Install app dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the application port (5000 as per your app's config)
EXPOSE 5000

# Start the application
CMD ["node", "main.js"]

