---
- name: Provision and Deploy Web Application
  hosts: localhost
  vars_files:
    - vault.yml

  roles:
    - provision

- name: Configure and Deploy Application on Droplet
  hosts: webserver
  become: true
  vars_files:
    - vault.yml

  roles:
    - setup
    - database
    - app
    - nginx

- name: Run post-deployment tests
  hosts: webserver
  become: true
  vars_files: 
    - vault.yml
  roles:
    - testing 
